name: Auto Create PR

on:
  push:
    branches:
      - 'feature/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Create Pull Request
        run: |
          gh pr create \
            --base "main" \
            --head "${{ github.ref_name }}" \
            --title "Auto PR - ${{ github.ref_name }}" \
            --body "PR criado automaticamente."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}