name: Auto Create PR

on:
  push:
    branches:
      - 'feature/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configura GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.PAT_TOKEN }}"
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Create Pull Request
        run: |
          echo "Criando PR da branch ${{ github.ref_name }} para main"
          gh pr create \
            --base "main" \
            --head "${{ github.ref_name }}" \
            --title "Auto PR - ${{ github.ref_name }}" \
            --body "PR criado automaticamente pelo workflow."
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}