name: CI + Auto PR

on:
  push:
    branches:
      - main
      - "feature/**"

  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:

  build:
    name: Build Project
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Build with Maven
        run: |
          cd app
          mvn clean install

  create-or-update-pr:
    name: Create or Update PR
    if: startsWith(github.ref, 'refs/heads/feature/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if PR already exists
        id: check_pr
        run: |
          PR_NUMBER=$(gh pr list \
            --head "${{ github.ref_name }}" \
            --base main \
            --json number \
            --jq '.[0].number')

          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR
        if: steps.check_pr.outputs.pr_number == ''
        run: |
          echo "Criando PR da branch ${{ github.ref_name }} → main"

          gh pr create \
            --base main \
            --head "${{ github.ref_name }}" \
            --title "feat: ${{ github.ref_name }}" \
            --body "Pull Request criado automaticamente pelo workflow."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: PR already exists
        if: steps.check_pr.outputs.pr_number != ''
        run: |
          echo "PR já existe: #${{ steps.check_pr.outputs.pr_number }}"